```{r}
source("R\\vegetation_indices.R")
drone_dataset <- "D:\\Datasets\\Drone_data_analysis_2025" 
drone_orthomosaic <- file.path(drone_dataset, "drone_Orthophotos") 
output_dir <- here::here("D:\\Datasets\\data_Rfabt_repo", "results", "2026")

here::here()
dir.exists(output_dir)
```

# Load image
```{r}
plt66_67_ortho <- (file.path(drone_orthomosaic, "plt_6667_mission1-all.tif"))
plt24_ortho <- (file.path(drone_orthomosaic, "plt_24_mission1-all.tif"))


```

## Calculate vegetation indices
```{r}
classify_matrix <- matrix(
  c(
  # from,  to,    class
    -Inf, 0.50,  0,    # no vegetation
    0.50,  Inf,   1   # Vegetation 
    
  ),
  ncol = 3, byrow = TRUE
)

plt24_EXGR <- vegetation_index(index_name = "ExGR", 
                                image_path = plt24_ortho,
                                output_path = file.path(output_dir, "vegetation_indices", "plt24_EXGR.tif"),
                                overwrite = TRUE)
                                

plt24_GLI <- vegetation_index(index_name = "GLI", 
                                image_path = plt24_ortho,
                                output_path = file.path(output_dir, "vegetation_indices", "plt24_GLI.tif"),
                                overwrite = TRUE)

plot(plt24_EXGR, main = "ExGR Index")
plot(plt24_GLI, main = "GLI Index")

```

# Classification of vegetation health
```{r}
# ── Define classification breaks ────────────────────────────────────────────
# Adjust thresholds based on your data range and field knowledge
classify_matrix <- matrix(
  c(
  # from,  to,    class
    -Inf, 0.50,  0,    # no vegetation
    0.50,  Inf,   1   # Vegetation 
    
  ),
  ncol = 3, byrow = TRUE
)

# ── Classify ────────────────────────────────────────────────────────────────
plt24_EXGR_class <- terra::classify(plt24_EXGR, classify_matrix, include.lowest = TRUE)
plt24_GLI_class <- terra::classify(plt24_GLI, classify_matrix, include.lowest = TRUE)

plot(plt24_GLI_class, main = "GLI Classification", type = "classes")
plot(plt24_EXGR_class, main = "EXGR Classification", type = "classes")
plto


# ── Assign class labels and colours ─────────────────────────────────────────
class_labels <- c(
  "Non-vegetation",
   "Vegetation"
)

class_colors <- c(
  "#d73027",   # red
  "#279d2d"  # green
  
)

# ── Set as categorical raster ───────────────────────────────────────────────
levels(plt24_vndvi_class) <- data.frame(id = 1:2, category = class_labels)
terra::coltab(plt24_vndvi_class) <- data.frame(
  value = 1:2,
  col   = class_colors
)

# ── Plot ────────────────────────────────────────────────────────────────────
plot(plt24_vndvi_class, main = "vNDVI Classification", type = "classes",
     col = class_colors, levels = class_labels)

# ── Save classified raster ──────────────────────────────────────────────────
terra::writeRaster(plt24_EXGR_class,
                   file.path(output_dir, "plt24_EXGR_classified.tif"),
                   overwrite = TRUE)
plot(plt24_EXGR_class)
```